language: python
notifications:
  slack: fossasia:jPhiT9cwjoLijkP54vTGqdJO
python:
  - "2.7"
install: pip install -r requirements.txt
before_script:
  - nvm install 4.4
  - nvm alias default 4.4
  - npm install
script:
  - sh build.sh
env:
  - secure: "MA928kGtPidi9F5ciZOogrQnNTZKWPESFq9ew9Mw0wVLu9evcJlFa5WoYXkmOn72hM8qEwoD66R7zb9b+0QS8uHop9QvjG1cjpslzorjE08BU0aMlsx98STPVWB5l8aNOPGE3qhFJmOWm6c+B8lNph61nTMR/4oQ+3+kFvMj4SX9QJ3zZ+VxP/Be5uMkpwySbH9t4rByI4dcvOnwpnsxeuxE7HktNUbuJeAh5nuWuWUgfDrvG2FGgp85zZBQtBTUVAb7ggLNJbdNz6hKOjrVYefqa0bOsoFjbyAtb2vNmfHSsg/xUfBQ/4SSsfYU5jv/uuyp+mdbEb0TLejMNjOCUsIq6bIUe2XgQHJhhHrEtZsUVQEC/1bckxgDFYbmDJcbOQt9j+QAppPkhAoq71IzOnycpmM5zGEZUoOxRIay//Dyg3QyPOJ0Jswce6zKuy8DV5K9aInGBscyY/6Q6Zab7vn0cOYhKEVMSzpKlz4TxGvQm8FGUOqaFFBoxoZlmjzyIeWYqiKRwt7FJgXKEyjbFn8uwt1lZze535eytVgW4Rx4g5QkW6HCQcsQQe0Shqkfb8feDICCw5xPLwUvutrU9/s9HCN/wxpE8nUHhGsODyUl41hCkvocL608wDutgJjhBrQod3wu81Bn8O+ZM/C0XUgvH5LAMxpaMVxg9lMs2Ns="
  - secure: "akRxPbr0R+M2pFCXCUD+pctbPitM6pydxl669vJydpKzRxn7k8GqHfQ7Sd4J/gg5JEaJaaMvr9vXFkje2ZHXX+XxzvL7GgaXDL93HVZ7Qtg98vWImttlRmw5YXVKMVWTFqkCuCU1rFA3E2Fsj6lqBdE9xYjCAts1j7uctsXJaD1qHD98F2NCRt4+k8ZctFqNwV+/5nGx699+KzkG/2xh3i2OHHYIFHlNfIBrlLbJSl1QNFkp9+8g/PTsy1Kwybb6kyyvUXCji5sqbmeNN4x2NivfsdRUcjGFJNVe387I/KbJBfccP3VeEe68dpN8oc1pzF1xrLiRUGzeYoDgedJGk9q180EyjWoOShf95ue/xB0hzubS+a7iQwlJ7sdmBrWQsaFRBIuxW3CvjthB63F8cLVYcffrZj+8LqN/BBbKYZR8UmyWu7tUzwuyqDDb6ssZ8TKhGob/fOBkVOQQjExbyITAoyJ5yH9x/SROuiaqy4SlW26i6lsX9wGRcN01RAafvtK2eMTwRT8aTbrJZmx52+K/cWAikuTxZByq7rU46rTZaXsGjfjAnP1yEmX1oyPqV2ZUKAyrx4QevzvfNDsVw8Vl+LNL4jQzYRgbFEiJzhGWHXRMqIKyMXFFSzBqxF0HRdtB5d4HzM/4Sb8RLwf/aDMvA43Brh7TsnJJ2euYph8="
